export const data = [
  {
    id: 1,
    name: "airPods-max",
    image: "1.png",
    price: 20,
    discount: 2,
    discountPrice: 20,
    quantity: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?",
  },
  {
    id: 2,
    name: "case iPhone11",
    image: "2.jpg",
    price: 30,
    discount: 5,
    discountPrice: 30,
    quantity: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?",
  },
  {
    id: 3,
    name: "headphones",
    image: "3.jpg",
    price: 15,
    discount: 3,
    discountPrice: 15,
    quantity: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?",
  },
  {
    id: 4,
    name: "apple charger",
    image: "4.jpg",
    price: 50,
    discount: 4,
    discountPrice: 50,
    quantity: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?",
  },
  {
    id: 5,
    name: "portable phone charger",
    image: "5.jpg",
    price: 25,
    discount: 2,
    discountPrice: 25,
    quantity: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?",
  },
  {
    id: 6,
    name: "selfie pulk",
    image: "6.jpg",
    price: 60,
    discount: 6,
    discountPrice: 60,
    quantity: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?",
  },
  {
    id: 7,
    name: "case for apple",
    image: "7.jpg",
    price: 35,
    discount: 2,
    discountPrice:  35,
    quantity: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?",
  },
  {
    id: 8,
    name: "charge cable for apple",
    image: "8.jpg",
    price: 80,
    discount: 7,
    discountPrice: 80,
    quantity: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?",
  },
  {
    id: 9,
    name: "case for Iphone 12",
    image: "9.jpg",
    price: 95,
    discount: 4,
    discountPrice: 95,
    quantity: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?",
  },
  {
    id: 10,
    name: "wireless earphone",
    image: "10.png",
    price: 120,
    discount: 3,
    discountPrice: 120,
    quantity: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?",
  },
];